services:
  # Next.js веб-приложение
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_web
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped 